config/routes.rb
Rails.application.routes.draw do

  post '/rooms' => 'rooms#create'

  post '/categories' => 'categories#create'

  get '/items' => 'items#index', as: :items
  post '/items' => 'items#create'
  patch '/items/:id' => 'items#update', as: :item
  delete '/items/:id' => 'items#destroy', as: :delete_item
  get '/items/refresh_item/:house_id' => 'items#refresh_item', as: :refresh_item
  get '/items/:id' => 'items#show', as: :show_item
  get '/house_items' => 'items#house_items', as: :house_items

  get '/inventory' => 'pages#inventory', as: :inventory
  get '/improvements' => 'pages#improvements', as: :improvements
  get '/settings' => 'pages#settings', as: :settings

  resources :houses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root to: "pages#inventory", as: :user_root
  end
  root to: 'pages#home'

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @houses = current_user.houses.all
    @rooms = current_user.rooms.all
    @items = current_user.items
    @categories = current_user.categories
    respond_with(@houses)
  end

  def show
    respond_with(@house)
  end

  def new
    @house = current_user.houses.new
    respond_with(@house)
  end

  def edit
  end

  def create
    @house = current_user.houses.new(house_params)
    @house.save
    redirect_to inventory_path
  end

  def update
    @house.update(house_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @house.destroy
    redirect_to inventory_path
  end

  private
    def set_house
      @house = House.find(params[:id])
    end

    def house_params
      params.require(:house).permit(:user_id, :name, :image, :address_attributes => [:line_1, :line_2, :number, :city, :zip, :state, :country])
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_create_house.html.erb
<h1>New House</h1>
<%= form_for("house", :url => '/houses') do |f| %> 
  <div class="row">
    <div class="large-6 columns">
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.fields_for :address_attributes do |ff| %>
        <div><%= ff.label :line_1 %><br />
        <%= ff.text_field :line_1 %></div>
        <div><%= ff.label :line_2 %><br />
        <%= ff.text_field :line_2 %></div>
        <div><%= ff.label :number %><br />
        <%= ff.text_field :number %></div>
      </div>
      <div class="large-6 columns">
        <div><%= ff.label :city %><br />
        <%= ff.text_field :city %></div>
        <div><%= ff.label :zip %><br />
        <%= ff.text_field :zip %></div>
        <div><%= ff.label :state %><br />
        <%= ff.text_field :state %></div>
        <div><%= ff.label :country %><br />
        <%= ff.text_field :country %></div>
        <%= f.submit "Create House", class: "button" %>
      <% end %>
    </div>
  </div>
<% end %> 

app/views/houses/_form.html.erb
<% @house.build_address if @house.address.nil? %>
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.fields_for :address do |ff| %>
    <div><%= ff.label :line_1 %><br />
    <%= ff.text_field :line_1 %></div>
    <div><%= ff.label :line_2 %><br />
    <%= ff.text_field :line_2 %></div>
    <div><%= ff.label :number %><br />
    <%= ff.text_field :number %></div>
    <div><%= ff.label :city %><br />
    <%= ff.text_field :city %></div>
    <div><%= ff.label :zip %><br />
    <%= ff.text_field :zip %></div>
    <div><%= ff.label :state %><br />
    <%= ff.text_field :state %></div>
    <div><%= ff.label :country %><br />
    <%= ff.text_field :country %></div>
  <% end %>
  <%= f.label :image %>
  <%= f.file_field :image %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/_new_house.html.erb
<h1>New House</h1>
<%= form_for("house", :url => '/houses') do |f| %> 
  <div class="row">
    <div class="large-6 columns">
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      <%= f.fields_for :address_attributes do |ff| %>
        <div><%= ff.label :line_1 %><br />
        <%= ff.text_field :line_1 %></div>
        <div><%= ff.label :line_2 %><br />
        <%= ff.text_field :line_2 %></div>
        <div><%= ff.label :number %><br />
        <%= ff.text_field :number %></div>
        <%= f.submit "Create House", class: "button" %>
      </div>
      <div class="large-6 columns">
        <div><%= ff.label :city %><br />
        <%= ff.text_field :city %></div>
        <div><%= ff.label :zip %><br />
        <%= ff.text_field :zip %></div>
        <div><%= ff.label :state %><br />
        <%= ff.text_field :state %></div>
        <div><%= ff.label :country %><br />
        <%= ff.text_field :country %></div>
      <% end %>
    </div>
  </div>
<% end %> 

app/views/houses/_show.html.erb
<%= image_tag house.image %><br />
<%= house.address.natural %><br />

<%= link_to "Edit", "#", "data-reveal-id" => "edit_house_#{@house.id}" %>
  <%= content_tag :div, id: "edit_house_#{@house.id}", class: "reveal-modal", "data-reveal" => true do %>
  <%= render 'houses/update_house', house: @house %>
  <%= link_to "&#215;".html_safe, "#", onclick: "$('#edit_house_#{@house.id.to_s}').foundation('reveal', 'close');", class: "close-reveal-modal" %> 
<% end %>|
<%= link_to "Delete", "/houses/#{house.id}", method: :delete, remote: true, :data => {confirm: "Are you sure you want to permanently delete this item?"} %>

app/views/houses/_update_house.html.erb
<h1>Update <%= house.name %></h1>
<%= form_for house, method: :patch, remote: true do |f| %> 
  <div class="row">
    <div class="large-6 columns">
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.fields_for :address do |ff| %>
        <div><%= ff.label :line_1 %><br />
        <%= ff.text_field :line_1 %></div>
        <div><%= ff.label :line_2 %><br />
        <%= ff.text_field :line_2 %></div>
        <div><%= ff.label :number %><br />
        <%= ff.text_field :number %></div>
      </div>
      <div class="large-6 columns">
        <div><%= ff.label :city %><br />
        <%= ff.text_field :city %></div>
        <div><%= ff.label :zip %><br />
        <%= ff.text_field :zip %></div>
        <div><%= ff.label :state %><br />
        <%= ff.text_field :state %></div>
        <div><%= ff.label :country %><br />
        <%= ff.text_field :country %></div>
        <%= f.submit "Update House", class: "button" %>
      <% end %>
    </div>
  </div>
<% end %> 

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<div class="row">
  <% @houses.each do |house| %>
    <%= link_to house_items_path(:house_id => house.id), remote: true do %>
      <div class="large-3 columns left">
        <%= house.name %><br />
        <%= house.address.natural %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="row">
  <div id="item_container">
    <h1>ITEMS GO HERE</h1>
  </div>
</div>
<a href="#" data-reveal-id="new_house" class="button">New House</a>

<div id="new_house" class="reveal-modal" data-reveal>
  <%= render 'new_house' %>
  <a class="close-reveal-modal">&#215;</a>
</div>

<a href="#" data-reveal-id="new_category" class="button">New Category</a>

<div id="new_category" class="reveal-modal" data-reveal>
  <%= render 'categories/create_category' %>
  <a class="close-reveal-modal">&#215;</a>
</div>

<a href="#" data-reveal-id="new_room" class="button">New Room</a>

<div id="new_room" class="reveal-modal" data-reveal>
  <%= render 'rooms/create_room' %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/update.js.erb
$(".reveal-modal.open").foundation('reveal', 'close');
$("#house_<%= escape_javascript(@house.id.to_s) %>").trigger("click");