config/routes.rb
Rails.application.routes.draw do

  post '/rooms' => 'rooms#create'

  post '/categories' => 'categories#create'

  get '/items' => 'items#index', as: :items
  post '/items' => 'items#create'
  patch '/items/:id' => 'items#update', as: :item
  delete '/items/:id' => 'items#destroy', as: :delete_item
  get '/items/refresh_item/:house_id' => 'items#refresh_item', as: :refresh_item
  get '/items/:id' => 'items#show', as: :show_item
  get '/house_items' => 'items#house_items', as: :house_items

  get '/inventory' => 'pages#inventory', as: :inventory
  get '/improvements' => 'pages#improvements', as: :improvements
  get '/settings' => 'pages#settings', as: :settings

  resources :houses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root to: "pages#inventory", as: :user_root
  end
  root to: 'pages#home'

end

app/views/pages/home.html.erb
<div class="row">
  <%= render 'devise/sessions/new_session' %>
</div>

app/views/pages/improvements.html.erb
<h1>Home Improvements</h1>
<h2>Coming soon!</h2>
<p>Home Improvments are worth tracking as well, as such we are currently working on an implimentation that allows you to efficiently track the improvmenets you've made on your home.</p>

app/views/pages/inventory.html.erb
<div class="row">
  <div class="large-2 columns">
    <div id="house_show">
      <!-- House Rendered Here -->
    </div>
  </div>
  <div class="large-10 columns">
    <div id="item_show">
      <!-- Item Rendered Here -->
    </div>
  </div>
</div>
<div class="row">
  <div class="large-2 columns" id="houses">
    <h1>Houses</h1>
    <% @houses.each do |house| %>
      <div class="row">
        <%= link_to house_items_path(:house_id => house.id), remote: true, class: "house", id: "house_#{house.id}", data: house.id do %>
          <div class="large-12 columns">
            <%= house.name %><br />
            <%= house.address.natural %><br /><br />
          </div>
        <% end %>
      </div>
    <% end %>
    <a href="#" data-reveal-id="new_house" class="button">New House</a>

    <div id="new_house" class="reveal-modal" data-reveal>
      <div id="create_house">
        <%= render 'houses/create_house' %>
      </div>
      <a class="close-reveal-modal">&#215;</a>
    </div>
  </div>
  <div class="large-10 columns">
    <h1>Items</h1>
    
    <a href="#" data-reveal-id="new_item" class="button">New Item</a>

    <div id="new_item" class="reveal-modal" data-reveal>
      <div id="create_item">
        <%= render 'items/create_item' %>
      </div>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <a href="#" data-reveal-id="new_category" class="button">New Category</a>

    <div id="new_category" class="reveal-modal" data-reveal>
      <div id="create_category">
        <%= render 'categories/create_category' %>
      </div>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <a href="#" data-reveal-id="new_room" class="button">New Room</a>

    <div id="new_room" class="reveal-modal" data-reveal>
      <div id="create_room">
        <%= render 'rooms/create_room' %>
      </div>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <%= link_to "Download CSV", items_path(format: :csv), class: "button success" %>
    <%= link_to "Download Excel", items_path(format: :xls), class: "button success" %>

    <div id="item_container">
      <!-- items partial gets populated here -->  
    </div>
  </div>
</div>

app/views/pages/settings.html.erb
settings.html.erb