config/routes.rb
Rails.application.routes.draw do

  post '/rooms' => 'rooms#create'

  post '/categories' => 'categories#create'

  get '/items' => 'items#index', as: :items
  post '/items' => 'items#create'
  patch '/items/:id' => 'items#update', as: :item
  delete '/items/:id' => 'items#destroy', as: :delete_item
  get '/items/refresh_item/:house_id' => 'items#refresh_item', as: :refresh_item
  get '/items/:id' => 'items#show', as: :show_item
  get '/house_items' => 'items#house_items', as: :house_items

  get '/inventory' => 'pages#inventory', as: :inventory
  get '/improvements' => 'pages#improvements', as: :improvements
  get '/settings' => 'pages#settings', as: :settings

  resources :houses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root to: "pages#inventory", as: :user_root
  end
  root to: 'pages#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :house
  belongs_to :room
  belongs_to :category
  has_one :user, through: :house

  mount_uploader :image, ImageUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = current_user.items
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"item_list.csv\""
        headers['Content-Type'] = 'text/csv'
      end
      format.xls
    end
  end

  def create
    @item = current_user.items.new(item_params)
    @item.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.js
    end
  end

  def update
    @item = current_user.items.find(params[:id])
    @item.update(item_params)
    respond_to do |format|
      format.js
    end
  end

  def show
    @item = current_user.items.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def house_items
    @items = current_user.houses.find(params[:house_id]).items
    @house = current_user.houses.find(params[:house_id])
    @house_options = current_user.houses.all.map { |house| [house.name, house.id] }
    @room_options = current_user.rooms.all.map { |room| [room.name, room.id] }
    @category_options = current_user.categories.all.map { |cat| [cat.name, cat.id] }
    respond_to do |format|
      format.js
    end
  end

  def refresh_item
    @house = current_user.houses.find(params[:house_id])
    @houses = current_user.houses.all
    @rooms = current_user.rooms.all
    @categories = current_user.categories
    @house_options = @houses.map { |house| [house.name, house.id] }
    @room_options = @rooms.map { |room| [room.name, room.id] }
    @category_options = @categories.map { |cat| [cat.name, cat.id] }
    respond_to do |format|
      format.js
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:house_id, :room_id, :category_id, :name, :make, :model, :quantity, :place_of_purchase, :purchase_price, :purchase_date, :replacement_price, :serial_number, :bar_code, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_create_item.html.erb
<h1>New Item</h1>
<%= form_for("item", :url => '/items', remote: true) do |f| %> 
  <div class="row">
    <div class="large-4 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :house_id %>
      <%= f.select :house_id, @house_options %>
      <%= f.label :room_id %>
      <%= f.select :room_id, @room_options %>
      <%= f.label :category_id %>
      <%= f.select :category_id, @category_options %>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, value: 1 %>
      <%= f.submit "Create Item", class: "button" %>
    </div>
    <div class="large-4 columns">
      <%= f.label :make %>
      <%= f.text_field :make %>
      <%= f.label :model %>
      <%= f.text_field :model %>
      <%= f.label :place_of_purchase %>
      <%= f.text_field :place_of_purchase %>
      <%= f.label :purchase_price %>
      <%= f.number_field :purchase_price, step: 0.01 %>
      <%= f.label :replacement_price %>
      <%= f.number_field :replacement_price, step: 0.01 %>
    </div>
    <div class="large-4 columns">
      <%= f.label :purchase_date %>
      <%= f.date_select :purchase_date, start_year: 1900, end_year: Date.today.year %>
      <%= f.label :serial_number %>
      <%= f.text_field :serial_number %>
      <%= f.label :bar_code %>
      <%= f.text_field :bar_code %>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
  </div>
<% end %> 

app/views/items/_item_grid.html.erb
<table>
  <tr>
    <th>
      Name
    </th>
    <th>
      Category
    </th>
    <th>
      Room
    </th>
    <th>
      Quantity
    </th>
    <th>
      Make
    </th>
    <th>
      Model
    </th>
    <th>
      Place of Purchase
    </th>
    <th>
      Purchase Date
    </th>
    <th>
      Purchase Price
    </th>
    <th>
      Replacement Price
    </th>
    <th>
      Serial Number
    </th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td>
        <%= link_to show_item_path(item.id), remote: true do %>
          <%= item.name %>
          <% unless item.image.nil? %>
            <%= image_tag item.image.thumb %>
          <% end %>
        <% end %>
      </td>
      <td>
        <% unless item.category.nil? %>
          <%= item.category.name %>
        <% else %>
          Uncategorized
        <% end %>
      </td>
      <td>
        <% unless item.room.nil? %>
          <%= item.room.name %>
        <% else %>
          No Room
        <% end %>
      </td>
      <td>
        <%= item.quantity %>
      </td>
      <td>
        <%= item.make %>
      </td>
      <td>
        <%= item.model %>
      </td>
      <td>
        <%= item.place_of_purchase %>
      </td>
      <td>
        <%= item.purchase_date %>
      </td>
      <td>
        <%= item.purchase_price %>
      </td>
      <td>
        <%= item.replacement_price %>
      </td>
      <td>
        <%= item.serial_number %>
      </td>
      <td>
        <%= link_to "Edit", "#", "data-reveal-id" => "edit_item_#{item.id}" %>
        <%= content_tag :div, id: "edit_item_#{item.id}", class: "reveal-modal", "data-reveal" => true do %>
          <%= render 'items/update_item', item: item, house_options: @house_options %>
          <%= link_to "&#215;".html_safe, "#", onclick: "$('#edit_item_#{item.id.to_s}').foundation('reveal', 'close');", class: "close-reveal-modal" %> 
        <% end %>
      </td>
      <td>
        <%= link_to "Delete", delete_item_path(item.id), method: :delete, remote: true, :data => {confirm: "Are you sure you want to permanently delete this item?"} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/items/_show_item.html.erb
<%= image_tag item.image %>
<%= item.name %>

app/views/items/_update_item.html.erb
<h1>Update <%= item.name %></h1>
<%= form_for item, method: :patch, remote: true do |f| %> 
  <div class="row">
    <div class="large-4 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :house_id %>
      <%= f.select :house_id, @house_options %>
      <%= f.label :room_id %>
      <%= f.select :room_id, @room_options %>
      <%= f.label :category_id %>
      <%= f.select :category_id, @category_options %>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, value: 1 %>
      <%= f.submit "Update Item", class: "button" %>
    </div>
    <div class="large-4 columns">
      <%= f.label :make %>
      <%= f.text_field :make %>
      <%= f.label :model %>
      <%= f.text_field :model %>
      <%= f.label :place_of_purchase %>
      <%= f.text_field :place_of_purchase %>
      <%= f.label :purchase_price %>
      <%= f.number_field :purchase_price, step: 0.01 %>
      <%= f.label :replacement_price %>
      <%= f.number_field :replacement_price, step: 0.01 %>
    </div>
    <div class="large-4 columns">
      <%= f.label :purchase_date %>
      <%= f.date_select :purchase_date, start_year: 1900, end_year: Date.today.year %>
      <%= f.label :serial_number %>
      <%= f.text_field :serial_number %>
      <%= f.label :bar_code %>
      <%= f.text_field :bar_code %>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
  </div>
<% end %> 

app/views/items/create.js.erb
$('a.close-reveal-modal').trigger('click');
$("#house_<%= escape_javascript(@item.house.id.to_s) %>").trigger("click");

app/views/items/destroy.js.erb
$("#house_<%= escape_javascript(@item.house.id.to_s) %>").trigger("click");

app/views/items/house_items.js.erb
$(".house.selected").removeClass("selected");
$("#item_container").html("<%= escape_javascript(render partial: 'item_grid', locals: { items: @items } ) %>"); 
$("#house_show").html("<%= escape_javascript(render partial: 'houses/show', locals: { house: @house } ) %>"); 
$("#house_<%= escape_javascript(@house.id.to_s) %>").addClass("selected");

app/views/items/index.csv.erb
<% headers = ['Name', 'Category', 'Room', 'Quantity', 'Make', 'Model', 'Place of Purchase', 'Purchase Date', 'Purchase Price', 'Replacement Price', 'Serial Number', 'Bar Code'] %>
<%= CSV.generate_line headers %>
<% @items.each do |item| %>
  <% if !item.category.nil? && !item.room.nil? %>
    <%= CSV.generate_line([item.name, item.category.name, item.room.name, item.quantity, item.make, item.model, item.place_of_purchase, item.purchase_date, item.purchase_price, item.replacement_price, item.serial_number, item.bar_code]) %>
  <% elsif item.category.nil? && !item.room.nil? %>
    <%= CSV.generate_line([item.name, 'uncategorized', item.room.name, item.quantity, item.make, item.model, item.place_of_purchase, item.purchase_date, item.purchase_price, item.replacement_price, item.serial_number, item.bar_code]) %>
  <% elsif !item.category.nil? && item.room.nil? %>
    <%= CSV.generate_line([item.name, item.category.name, 'no room', item.quantity, item.make, item.model, item.place_of_purchase, item.purchase_date, item.purchase_price, item.replacement_price, item.serial_number, item.bar_code]) %>
  <% else %>
    <%= CSV.generate_line([item.name, 'uncategorized', 'no room', item.quantity, item.make, item.model, item.place_of_purchase, item.purchase_date, item.purchase_price, item.replacement_price, item.serial_number, item.bar_code]) %>
  <% end %>
<% end %>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <%= item.name %><br />
  <%= item.user.email %><br />
<% end %>

app/views/items/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Category</Data></Cell>
        <Cell><Data ss:Type="String">Room</Data></Cell>
        <Cell><Data ss:Type="String">Quantity</Data></Cell>
        <Cell><Data ss:Type="String">Make</Data></Cell>
        <Cell><Data ss:Type="String">Model</Data></Cell>
        <Cell><Data ss:Type="String">Place of Purchase</Data></Cell>
        <Cell><Data ss:Type="String">Purchase Date</Data></Cell>
        <Cell><Data ss:Type="String">Purchase Price</Data></Cell>
        <Cell><Data ss:Type="String">Replacement Price</Data></Cell>
        <Cell><Data ss:Type="String">Serial Number</Data></Cell>
        <Cell><Data ss:Type="String">Bar Code</Data></Cell>
      </Row>
    <% @items.each do |item| %>
      <Row>
        <Cell><Data ss:Type="String"><%= item.name %></Data></Cell>
        <% if !item.category.nil? %>
          <Cell><Data ss:Type="String"><%= item.category.name %></Data></Cell>
        <% else %>
          <Cell><Data ss:Type="String">uncategorized</Data></Cell>
        <% end %>
        <% if !item.room.nil? %>
          <Cell><Data ss:Type="String"><%= item.room.name %></Data></Cell>
        <% else %>
          <Cell><Data ss:Type="String">no room</Data></Cell>
        <% end %>
        <Cell><Data ss:Type="Number"><%= item.quantity %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.make %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.model %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.place_of_purchase %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= item.purchase_date %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= item.purchase_price %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= item.replacement_price %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.serial_number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.bar_code %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/items/refresh_item.js.erb
$('a.close-reveal-modal').trigger('click');
$("#create_item").html("<%= escape_javascript(render 'items/create_item', locals: { house_options: @house_options, item_options: @item_options, room_options: @room_options } ) %>");
$("#house_<%= escape_javascript(@house.id.to_s) %>").trigger("click");

app/views/items/show.js.erb
$("#item_show").html("<%= escape_javascript(render partial: 'items/show_item', locals: { item: @item } ) %>"); 

app/views/items/update.js.erb
$(".reveal-modal.open").foundation('reveal', 'close');
$("#house_<%= escape_javascript(@item.house.id.to_s) %>").trigger("click");