config/routes.rb
Rails.application.routes.draw do

  post '/rooms' => 'rooms#create'

  post '/categories' => 'categories#create'

  get '/items' => 'items#index', as: :items
  post '/items' => 'items#create'
  patch '/items/:id' => 'items#update', as: :item
  delete '/items/:id' => 'items#destroy', as: :delete_item
  get '/items/refresh_item/:house_id' => 'items#refresh_item', as: :refresh_item
  get '/items/:id' => 'items#show', as: :show_item
  get '/house_items' => 'items#house_items', as: :house_items

  get '/inventory' => 'pages#inventory', as: :inventory
  get '/improvements' => 'pages#improvements', as: :improvements
  get '/settings' => 'pages#settings', as: :settings

  resources :houses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root to: "pages#inventory", as: :user_root
  end
  root to: 'pages#home'

end

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "HouseStache", root_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <% if user_signed_in? %>
      <ul class="left">
        <li class="divider"></li>
        <li>
          <%= link_to "Inventory", inventory_path %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to "Improvements", improvements_path %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to "Settings", settings_path %>
        </li>
        <li class="divider"></li>
      </ul>
    <% end  %>
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "HouseStache" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="row">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>